apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobeinabox-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobeinabox-{{ default "staging" .Release.Namespace }}
  template:
    metadata:
      labels:
        app: jobeinabox-{{ default "staging" .Release.Namespace }}
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
        checksum/config: {{ include (print $.Template.BasePath "/jobeinabox-ingress.yaml") . | sha256sum }}
    spec:
      containers:
      - name: jobeinabox-{{ default "staging" .Release.Namespace }}
        image: {{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "250Mi"
            cpu: "200m" #0.2 CPU
          limits:
            memory: "1000Mi"
            cpu: "1000m" #1 CPU
        volumeMounts:
        - mountPath: /opt/R
          name: mountr
          readOnly: true
        - mountPath: /opt/python
          name: mountpython
          readOnly: true
        - mountPath: /opt/anaconda
          name: mountpython
          readOnly: true          
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}          
      volumes:
      - name: mountr
        persistentVolumeClaim:
          claimName: pvc-software-r-{{ default "staging" .Release.Namespace }}
          readOnly: true
      - name: mountpython
        persistentVolumeClaim:
          claimName: pvc-software-python-{{ default "staging" .Release.Namespace }}
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: jobeinabox-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: jobeinabox-{{ default "staging" .Release.Namespace }}
---
{{ if eq .Release.Namespace "production" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jobeinabox-{{ default "staging" .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jobeinabox-{{ default "staging" .Release.Namespace }}
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
{{- end }}
