apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobeinabox-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: jobeinabox-{{ default "staging" .Release.Namespace }}
  template:
    metadata:
      labels:
        app: jobeinabox-{{ default "staging" .Release.Namespace }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/jobeinabox-httproute.yaml") . | sha256sum }}
    spec:
      containers:
      - name: jobeinabox-{{ default "staging" .Release.Namespace }}
        image: "{{- if hasPrefix "harbor.cs.calvin.edu/calvincs-private/" .Values.image.name -}}{{ .Values.image.name }}:{{ .Values.image.tag }}{{- else -}}{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}{{- end }}"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1000Mi"
            cpu: "500m" #0.5 CPU
          limits:
            memory: "4000Mi"
            cpu: "4000m" #4 CPU
        volumeMounts:
        - mountPath: /opt/R
          name: mountr
          readOnly: true
        - mountPath: /opt/python
          name: mountpython
          readOnly: true
        - mountPath: /opt/anaconda
          name: mountpython
          readOnly: true          
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}          
      volumes:
      - name: mountr
        persistentVolumeClaim:
          claimName: pvc-software-r-{{ default "staging" .Release.Namespace }}
          readOnly: true
      - name: mountpython
        persistentVolumeClaim:
          claimName: pvc-software-python-{{ default "staging" .Release.Namespace }}
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: jobeinabox-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: jobeinabox-{{ default "staging" .Release.Namespace }}
---
{{ if eq .Release.Namespace "production" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jobeinabox-{{ default "staging" .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jobeinabox-{{ default "staging" .Release.Namespace }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetMemoryUtilizationPercentage }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleUp.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.hpa.behavior.scaleUp.selectPolicy }}
      policies:
{{ toYaml .Values.hpa.behavior.scaleUp.policies | nindent 6 }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleDown.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.hpa.behavior.scaleDown.selectPolicy }}
      policies:
{{ toYaml .Values.hpa.behavior.scaleDown.policies | nindent 6 }}
{{- end }}
