apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobe-{{ default "staging" .Release.Namespace }}-ingress
  namespace: {{ default "staging" .Release.Namespace }}
  annotations:
    ingressClassName: nginx   ## Broken with external-dns on AKS, only use for K3S
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: jobe{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.{{ .Values.dns.name }}
    external-dns.alpha.kubernetes.io/ttl: "60"  
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($apikey_is_ok != 1) {
      return 401;
      }
spec:
  tls:
  - hosts:
    - jobe{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.{{ .Values.dns.name }}
    secretName: tls-secret-jobe-{{ default "staging" .Release.Namespace }}
  rules:
  - host: jobe{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.{{ .Values.dns.name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jobeinabox-{{ default "staging" .Release.Namespace }}
            port:
              number: 80
