apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobeinabox-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobeinabox-{{ default "staging" .Release.Namespace }}
  template:
    metadata:
      labels:
        app: jobeinabox-{{ default "staging" .Release.Namespace }}
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
        checksum/config: {{ include (print $.Template.BasePath "/jobeinabox-ingress.yaml") . | sha256sum }}
    spec:
      nodeSelector:
        CSInfrastructure: "true"
      containers:
      - name: jobeinabox-{{ default "staging" .Release.Namespace }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /opt/R
          name: mountr
          readOnly: true
        - mountPath: /opt/anaconda
          name: mountanaconda
          readOnly: true
        - mountPath: /opt/python
          name: mountpython
          readOnly: true
      volumes:
      - name: mountr
        persistentVolumeClaim:
          claimName: pvc-nfs-r-int-r-{{ default "staging" .Release.Namespace }}
      - name: mountanaconda
        persistentVolumeClaim:
          claimName: pvc-nfs-r-int-anaconda-{{ default "staging" .Release.Namespace }}
      - name: mountpython
        persistentVolumeClaim:
          claimName: pvc-nfs-r-int-python-{{ default "staging" .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: jobeinabox-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: jobeinabox-{{ default "staging" .Release.Namespace }}
