name: Only build latest image

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_push_image:
    runs-on: ubuntu-24.04
    env:
      IMAGE_NAME: ${{secrets.HARBOR_NAME}}/calvincs-private/jobeinabox
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Docker Harbor Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_NAME }}
          username: ${{ secrets.HARBOR_LOGIN }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' && 'true' || 'false' }},priority=100
            type=raw,value=staging,enable=${{ github.ref == 'refs/heads/master' && 'false' || 'true' }},priority=100
            type=raw,value=${{ github.ref_name }}-${{ steps.short-sha.outputs.sha }},priority=200

      - name: Build and push production images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
