name: Deploy to staging

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      NAMESPACE: staging
      IMAGETAG: staging
    steps:
      - uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha    
      
      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K3S_ONPREM_KUBECONFIG }}
        id: setcontext    

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: latest

      - name: Make Wireguard connection
        run: |
          sudo apt install -y wireguard
          echo "${{ secrets.WG_PRIVATEKEY }}" > privatekey
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 172.16.201.2/29 peer 172.16.201.1
          sudo wg set wg0 listen-port 48123 private-key privatekey peer Et85fpcfQY6PdPE95gNo/J1D+FqCG6g88Ly59CZTfGw= allowed-ips ${{ secrets.WG_ALLOWEDIPS }} endpoint ${{ secrets.WG_HOST }}:${{ secrets.WG_PORT }}
          sudo ip link set up dev wg0
          sleep 5
          ping 153.106.195.1
          ping k3s1.cs.calvin.edu          

      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --atomic \
            --wait \
            --namespace ${{ env.NAMESPACE }} \
            jobeinabox \
           ./kubernetes/jobeinabox \
            --set image.repository=${{ secrets.ACR_NAME }} \
            --set image.tag=${{ env.IMAGETAG }}
